{% set name = "slimit" %}
{% set version = "0.8.1" %}
{% set revision = "3533eba9ad5b39f3a015ae6269670022ab310847" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
# update source to git archive as no release available for Python 3 updated version
source:
  url: "https://github.com/rspivak/{{ name }}/archive/{{ revision }}.tar.gz" # https://github.com/rspivak/slimit/archive/{{ revision }}.tar.gz
  sha256: "af3d208099218a4d5265e1ed06960b0260b39bf6849bfb80bac2c274758700ad"

build:
  number: 5
  skip: true  # [py<313]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - ply >=3.11
test:
  imports:
    - slimit
    - slimit.tests

about:
  home: "https://github.com/rspivak/slimit"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "SlimIt is a JavaScript minifier written in Python. It compiles JavaScript into more compact code so that it downloads and runs faster."
  doc_url: "https://slimit.readthedocs.io/"
  dev_url: "https://github.com/rspivak/slimit"

extra:
  recipe-maintainers:
    - agcopenhaver
    - oblute
    - rluria14
